const users = [
  {
    id: 1,
    name: "Aquila Jedidiah",
    school: "Karatina University",
    streetAddress: "P.O. Box 123, Soy",
    gender: "Male",
    email: "aquila.jedidiah@example.com",
    phone: "0712345678",
  },
  {
    id: 2,
    name: "Grace Wanjiku",
    school: "University of Nairobi",
    streetAddress: "Tom Mboya Street, Nairobi",
    gender: "Female",
    email: "grace.wanjiku@example.com",
    phone: "0712456789",
  },
  {
    id: 3,
    name: "Kevin Otieno",
    school: "Jomo Kenyatta University",
    streetAddress: "Juja Town, Kiambu",
    gender: "Male",
    email: "kevin.otieno@example.com",
    phone: "0712567890",
  },
  {
    id: 4,
    name: "Faith Chebet",
    school: "Moi University",
    streetAddress: "Kesses, Eldoret",
    gender: "Female",
    email: "faith.chebet@example.com",
    phone: "0712678901",
  },
  {
    id: 5,
    name: "Brian Mwangi",
    school: "Mount Kenya University",
    streetAddress: "Thika Road, Thika",
    gender: "Male",
    email: "brian.mwangi@example.com",
    phone: "0712789012",
  },
  {
    id: 6,
    name: "Linet Wairimu",
    school: "Maseno University",
    streetAddress: "Maseno Town, Kisumu",
    gender: "Female",
    email: "linet.wairimu@example.com",
    phone: "0712890123",
  },
  {
    id: 7,
    name: "John Kiptoo",
    school: "Egerton University",
    streetAddress: "Njoro, Nakuru",
    gender: "Male",
    email: "john.kiptoo@example.com",
    phone: "0712901234",
  },
  {
    id: 8,
    name: "Mercy Achieng",
    school: "Masinde Muliro University",
    streetAddress: "Kakamega Town",
    gender: "Female",
    email: "mercy.achieng@example.com",
    phone: "0713012345",
  },
  {
    id: 9,
    name: "Daniel Njoroge",
    school: "Chuka University",
    streetAddress: "Chuka, Embu",
    gender: "Male",
    email: "daniel.njoroge@example.com",
    phone: "0713123456",
  },
  {
    id: 10,
    name: "Susan Nduta",
    school: "Kenyatta University",
    streetAddress: "Kahawa, Nairobi",
    gender: "Female",
    email: "susan.nduta@example.com",
    phone: "0713234567",
  },
];

export default users;
